name: Auto-merge Claude PRs

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'claude/')
    steps:
      - name: Wait for other checks
        run: sleep 10

      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            console.log(`Auto-merging PR #${pr.number} from branch ${pr.head.ref}`);

            try {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                merge_method: 'squash',
                commit_title: pr.title,
                commit_message: `${pr.body || ''}\n\nAuto-merged by Claude Code workflow`
              });

              console.log('✅ PR merged successfully!');

              // Add a comment to confirm auto-merge
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: '🤖 This PR was automatically merged by Claude Code workflow.'
              });

            } catch (error) {
              console.error('Failed to merge PR:', error);

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `⚠️ Auto-merge failed: ${error.message}\n\nPlease merge manually.`
              });
            }
